import {
  javascript,
  typescript,
  html,
  css,
  reactjs,
  tailwind,
  nodejs,
  git,
  docker,
  sap,
  accenture,
  grab,
  sprout,
  portfoliopic1,
  projectSapAiml,
  projectAccentureMl,
  projectAccentureBackend,
  projectSproutData,
  python,
  sqlicon,
} from "../assets";

export const navLinks = [
  { id: "about", title: "About" },
  { id: "resume", title: "Resume", external: true },
  { id: "projects", title: "Projects" },
  { id: "work", title: "Work" },
  { id: "contact", title: "Contact" },
];

export const contactInfo = {
  email: "timothy.calder.dev@gmail.com",
  phone: "1 339 365-7217",
  phoneTel: "+13393657217",
  location: "Makati, National Capital Region, Philippines",
};

const expertiseAreas = [
  {
    title: "Production ML & Model Serving",
    description:
      "End-to-end ML platforms with model-serving APIs, experiment tracking, and containerized deployment on AWS and Kubernetes.",
    highlights: ["45% less manual review", "35% lower API latency"],
    skills: ["FastAPI", "TensorFlow", "PyTorch", "MLflow"],
    accent: "from-violet-600/20 to-purple-900/10",
    border: "group-hover:border-violet-500/40",
    icon: "ml",
  },
  {
    title: "LLM & Enterprise RAG",
    description:
      "Retrieval-augmented workflows with embeddings, vector search, prompt orchestration, and production guardrails for knowledge systems.",
    highlights: ["Grounded responses", "Fallback handling"],
    skills: ["RAG", "LangChain", "pgvector", "Embeddings"],
    accent: "from-cyan-600/20 to-blue-900/10",
    border: "group-hover:border-cyan-500/40",
    icon: "llm",
  },
  {
    title: "Cloud Backend & Microservices",
    description:
      "Scalable REST APIs and microservices for enterprise platforms — optimized SQL, caching, and CI/CD across distributed teams.",
    highlights: ["50% faster deploys", "35% ops automation"],
    skills: ["REST APIs", "PostgreSQL", "Docker", "Kubernetes"],
    accent: "from-amber-600/20 to-orange-900/10",
    border: "group-hover:border-amber-500/40",
    icon: "backend",
  },
  {
    title: "Data Engineering & Pipelines",
    description:
      "Reliable ETL pipelines, SQL data models, and validation workflows that feed analytics, BI dashboards, and ML feature stores.",
    highlights: ["40% faster processing", "BI-ready datasets"],
    skills: ["ETL", "SQL", "Warehousing", "Validation"],
    accent: "from-emerald-600/20 to-green-900/10",
    border: "group-hover:border-emerald-500/40",
    icon: "data",
  },
];

const careerHighlights = [
  { value: "10+", label: "Years Experience" },
  { value: "5", label: "Enterprise Roles" },
  { value: "45%", label: "Automation Gain" },
  { value: "35%", label: "Latency Reduced" },
];

const technologies = [
  { name: "Python", icon: python },
  { name: "SQL", icon: sqlicon },
  { name: "JavaScript", icon: javascript },
  { name: "TypeScript", icon: typescript },
  { name: "React", icon: reactjs },
  { name: "Node.js", icon: nodejs },
  { name: "Tailwind", icon: tailwind },
  { name: "Git", icon: git },
  { name: "Docker", icon: docker },
  { name: "HTML5", icon: html },
  { name: "CSS3", icon: css },
];

const tools = [
  {
    category: "AI / Machine Learning",
    items: [
      "Machine Learning",
      "Deep Learning",
      "Recommendation Systems",
      "Predictive Modeling",
      "Feature Engineering",
      "Model Evaluation",
      "Batch Inference",
      "Real-Time Inference",
    ],
  },
  {
    category: "Generative AI / LLM",
    items: [
      "RAG",
      "Embeddings",
      "Vector Search",
      "Prompt Engineering",
      "AI Agents",
      "LangChain",
      "LangGraph",
      "Guardrails",
      "LLM Evaluation",
    ],
  },
  {
    category: "Frameworks & Libraries",
    items: [
      "FastAPI",
      "Flask",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Pandas",
      "NumPy",
    ],
  },
  {
    category: "Cloud & DevOps",
    items: [
      "AWS",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Linux",
      "Microservices",
      "REST APIs",
    ],
  },
  {
    category: "Data Engineering",
    items: [
      "ETL Pipelines",
      "Data Modeling",
      "Data Warehousing",
      "SQL Optimization",
      "Batch Processing",
      "Distributed Data Systems",
    ],
  },
  {
    category: "Databases",
    items: [
      "PostgreSQL",
      "MySQL",
      "SQL Server",
      "NoSQL",
      "Vector Databases",
      "pgvector",
    ],
  },
  {
    category: "MLOps & Observability",
    items: [
      "MLflow",
      "Model Registry",
      "Experiment Tracking",
      "Model Monitoring",
      "Drift Detection",
      "Logging",
      "Metrics",
      "Tracing",
    ],
  },
];

const experiences = [
  {
    title: "Senior AI / ML Engineer",
    company_name: "SAP — Waldorf, Germany (Remote)",
    icon: sap,
    iconBg: "#ffffff",
    date: "Jan 2023 — Present",
    points: [
      "Designed scalable AI/ML enterprise applications using Python, FastAPI, AWS, Docker, and Kubernetes for production cloud environments.",
      "Built model-serving APIs and backend services integrating ML outputs into enterprise workflows, reducing manual review work by ~45%.",
      "Developed ML pipelines for data preparation, feature engineering, model integration, validation, and deployment across distributed systems.",
      "Implemented LLM automation with retrieval, prompt orchestration, grounding, response validation, and fallback handling for knowledge workflows.",
      "Built retrieval workflows using embeddings, metadata filtering, vector search, and API-based context assembly to improve answer relevance.",
      "Improved API performance through caching, query optimization, async processing, and container tuning, cutting average latency by ~35%.",
      "Deployed containerized AI/ML services via Docker, Kubernetes, and CI/CD, improving release consistency and reducing deployment effort by ~50%.",
      "Collaborated with international engineering teams across Europe and Asia on scalable AI, backend, and data architecture.",
    ],
  },
  {
    title: "Machine Learning Engineer",
    company_name: "Accenture Philippines — Mandaluyong (Hybrid)",
    icon: accenture,
    iconBg: "#ffffff",
    date: "Feb 2021 — Dec 2022",
    points: [
      "Developed scalable ML models and recommendation systems using Python, TensorFlow, PyTorch, SQL, and distributed data workflows.",
      "Built feature engineering pipelines transforming user activity, transactional data, and historical records into model-ready datasets.",
      "Designed recommendation logic and predictive models for personalization, ranking, classification, and intelligent automation.",
      "Created training, validation, and evaluation workflows to compare model performance and improve prediction quality.",
      "Integrated ML models into backend APIs and enterprise applications for reliable production consumption.",
      "Improved model evaluation and retraining workflows, reducing manual experimentation time by ~40%.",
      "Built batch inference pipelines for large-scale data processing and recurring prediction jobs.",
    ],
  },
  {
    title: "Senior Software Engineer",
    company_name: "Accenture Philippines — Mandaluyong (Hybrid)",
    icon: accenture,
    iconBg: "#ffffff",
    date: "Apr 2018 — Jan 2021",
    points: [
      "Designed and built scalable backend systems, enterprise APIs, and microservices for cloud-native business applications.",
      "Developed production-grade REST APIs used by internal platforms, automation workflows, and client-facing enterprise systems.",
      "Improved service reliability, database performance, and API response times through SQL optimization, caching, and refactoring.",
      "Integrated data-driven automation into enterprise applications, reducing repetitive operational tasks by ~35%.",
      "Contributed to architecture decisions for microservices, API contracts, database schema design, and deployment practices.",
      "Mentored junior engineers through code reviews, debugging support, documentation, and development best practices.",
    ],
  },
  {
    title: "Senior Backend Developer",
    company_name: "Grab — Singapore (Remote)",
    icon: grab,
    iconBg: "#ffffff",
    date: "Jan 2016 — Mar 2018",
    points: [
      "Built scalable backend services and high-performance APIs for cloud-integrated applications and automation systems.",
      "Developed microservices and API integrations supporting platform operations, internal tools, and regional business workflows.",
      "Improved backend infrastructure, database query performance, and service reliability for high-traffic environments.",
      "Designed SQL data models and optimized database access patterns for faster reporting and platform analytics.",
      "Built automation services that reduced manual operational work and improved team productivity.",
      "Collaborated with distributed engineering teams to deliver reliable backend features in agile release cycles.",
    ],
  },
  {
    title: "Data Engineer",
    company_name: "Sprout Solutions — Philippines (On-site)",
    icon: sprout,
    iconBg: "#ffffff",
    date: "Jan 2014 — May 2016",
    points: [
      "Built and optimized ETL pipelines and enterprise data workflows for analytics, reporting, and business intelligence.",
      "Developed SQL-based data models for operational reporting, dashboards, and downstream analytics use cases.",
      "Improved pipeline reliability through validation checks, transformation rules, error handling, and scheduled processing.",
      "Optimized complex SQL queries and reporting workflows, reducing data processing time by ~40%.",
      "Prepared clean, structured datasets supporting analytics, automation, and data-driven decision-making.",
      "Worked with business teams to translate reporting requirements into reliable data pipelines.",
    ],
  },
];

const projects = [
  {
    name: "Enterprise AI/ML Platform",
    company: "SAP",
    companyLogo: sap,
    role: "Senior AI / ML Engineer",
    period: "2023 — Present",
    category: "Enterprise AI Platform",
    metric: "45% less manual review",
    coverGradient: "from-[#0a2a5e] via-[#1d1836] to-[#0f0c29]",
    description:
      "Production AI/ML platform powering model-serving APIs, LLM retrieval workflows, and Kubernetes-based deployment for global enterprise teams.",
    detailedDescription:
      "Led development of SAP's enterprise AI/ML platform — a production system serving machine learning and LLM capabilities to business workflows across distributed cloud environments.\n\nRole & scope:\n\n• Senior AI/ML Engineer on a cross-regional team (Europe & Asia)\n• End-to-end ownership from API design through model deployment and monitoring\n• Internal enterprise platform — not publicly accessible\n\nKey outcomes:\n\n• Reduced manual review workload by ~45% through ML-integrated automation\n• Cut average API latency by ~35% via caching, async processing, and container tuning\n• Reduced deployment effort by ~50% with Docker, Kubernetes, and CI/CD pipelines\n\nTechnical delivery:\n\n• Model-serving REST APIs built with FastAPI on AWS\n• RAG workflows with embeddings, vector search, and response validation\n• ML pipelines for feature engineering, validation, and production deployment\n• MLflow experiment tracking, structured logging, and health monitoring",
    hideVideo: true,
    dataIntegration:
      "Architecture: Client apps → FastAPI model-serving layer → ML inference workers → PostgreSQL / vector store → monitoring & logging stack.\n\nDeployment: AWS, Docker, Kubernetes, CI/CD. LLM patterns include retrieval, prompt orchestration, grounding, guardrails, and fallback handling.\n\nStack: Python, FastAPI, TensorFlow, PyTorch, MLflow, LangChain, LangGraph, PostgreSQL, pgvector.",
    tags: [
      { name: "fastapi", color: "blue-text-gradient" },
      { name: "kubernetes", color: "green-text-gradient" },
      { name: "llm-rag", color: "pink-text-gradient" },
    ],
    techStack: [
      "Python",
      "FastAPI",
      "AWS",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "TensorFlow",
      "PyTorch",
      "MLflow",
      "LangChain",
      "LangGraph",
      "Embeddings",
      "Vector Search",
    ],
    image: projectSapAiml,
    images: [
      { src: projectSapAiml, caption: "Platform overview — model serving metrics, API health, and RAG pipeline monitoring" },
    ],
    source_code_link: "",
    videoUrl: "",
    liveDemo: "",
    enterprise: true,
  },
  {
    name: "Recommendation & Automation Platform",
    company: "Accenture",
    companyLogo: accenture,
    role: "Machine Learning Engineer",
    period: "2021 — 2022",
    category: "ML & Recommendations",
    metric: "40% faster experimentation",
    coverGradient: "from-[#4a0072] via-[#1d1836] to-[#0f0c29]",
    description:
      "Enterprise recommendation engine and intelligent automation platform — feature pipelines, model training, and production APIs for client-facing systems.",
    detailedDescription:
      "Built Accenture's recommendation and intelligent automation platform for enterprise clients requiring personalization, ranking, and predictive decision support at scale.\n\nRole & scope:\n\n• Machine Learning Engineer on a hybrid delivery team in Mandaluyong\n• Owned feature pipelines, model training workflows, and API integration\n• Client-facing enterprise platform with strict SLA requirements\n\nKey outcomes:\n\n• Reduced manual ML experimentation time by ~40% through automated retraining workflows\n• Improved prediction quality with structured train/validate/evaluate pipelines\n• Delivered batch inference at scale for recurring enterprise prediction jobs\n\nTechnical delivery:\n\n• Recommendation, ranking, and classification models with TensorFlow and PyTorch\n• Feature engineering from user activity, transactions, and operational signals\n• Production REST APIs exposing model outputs to business applications\n• Cloud-based monitoring for model reliability and performance",
    hideVideo: true,
    dataIntegration:
      "Architecture: Data sources → feature engineering pipeline → model training & registry → batch/real-time inference → REST API layer → client applications.\n\nStack: Python, TensorFlow, PyTorch, Scikit-learn, SQL, FastAPI, PostgreSQL, Pandas, NumPy, Docker, AWS.",
    tags: [
      { name: "tensorflow", color: "blue-text-gradient" },
      { name: "recommendations", color: "green-text-gradient" },
      { name: "ml-pipelines", color: "pink-text-gradient" },
    ],
    techStack: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "SQL",
      "FastAPI",
      "PostgreSQL",
      "Pandas",
      "NumPy",
      "Docker",
      "AWS",
    ],
    image: projectAccentureMl,
    images: [
      { src: projectAccentureMl, caption: "ML platform dashboard — recommendation metrics, model performance, and pipeline status" },
    ],
    source_code_link: "",
    videoUrl: "",
    liveDemo: "",
    enterprise: true,
  },
  {
    name: "Cloud-Native Backend Platform",
    company: "Accenture",
    companyLogo: accenture,
    role: "Senior Software Engineer",
    period: "2018 — 2021",
    category: "Backend & Microservices",
    metric: "35% ops automation",
    coverGradient: "from-[#1e3a5f] via-[#1d1836] to-[#0f0c29]",
    description:
      "Cloud-native microservices platform with production REST APIs, SQL-optimized data layers, and automation services for enterprise business applications.",
    detailedDescription:
      "Designed and delivered Accenture's cloud-native backend platform supporting internal tools, client-facing enterprise systems, and data-driven automation workflows.\n\nRole & scope:\n\n• Senior Software Engineer leading backend architecture and API design\n• Cross-functional delivery with QA, DevOps, and product teams\n• Multi-year platform evolution from legacy systems to cloud-ready services\n\nKey outcomes:\n\n• Reduced repetitive operational tasks by ~35% through integrated automation\n• Improved API response times via SQL optimization, caching, and refactoring\n• Mentored junior engineers on code quality, debugging, and best practices\n\nTechnical delivery:\n\n• Microservices architecture with production REST APIs\n• PostgreSQL and MySQL schema design with performance tuning\n• CI/CD deployment pipelines on AWS with Docker\n• Early ML-assisted business logic integrated into backend services",
    hideVideo: true,
    dataIntegration:
      "Architecture: API gateway → microservices layer → database tier (PostgreSQL / MySQL) → caching & message queues → monitoring.\n\nStack: Java, Python, TypeScript, REST APIs, PostgreSQL, MySQL, Docker, AWS, CI/CD, Linux.",
    tags: [
      { name: "microservices", color: "blue-text-gradient" },
      { name: "rest-apis", color: "green-text-gradient" },
      { name: "cloud-native", color: "pink-text-gradient" },
    ],
    techStack: [
      "Java",
      "Python",
      "SQL",
      "TypeScript",
      "REST APIs",
      "PostgreSQL",
      "MySQL",
      "Docker",
      "AWS",
      "CI/CD",
    ],
    image: projectAccentureBackend,
    images: [
      { src: projectAccentureBackend, caption: "Backend platform — service health, API gateway metrics, and microservices topology" },
    ],
    source_code_link: "",
    videoUrl: "",
    liveDemo: "",
    enterprise: true,
  },
  {
    name: "Enterprise Data Processing Platform",
    company: "Sprout Solutions",
    companyLogo: sprout,
    role: "Data Engineer",
    period: "2014 — 2016",
    category: "Data Engineering & BI",
    metric: "40% faster processing",
    coverGradient: "from-[#1a4d3a] via-[#1d1836] to-[#0f0c29]",
    description:
      "Enterprise ETL and analytics platform — SQL data models, validation workflows, and BI-ready datasets for operational reporting across the business.",
    detailedDescription:
      "Built Sprout Solutions' enterprise data processing platform enabling reliable analytics, reporting, and business intelligence for internal stakeholders.\n\nRole & scope:\n\n• Data Engineer on-site in the Philippines\n• Owned ETL pipeline design, SQL modeling, and data quality validation\n• Partnered directly with business teams on reporting requirements\n\nKey outcomes:\n\n• Reduced data processing time by ~40% through SQL and workflow optimization\n• Improved pipeline reliability with validation rules and scheduled processing\n• Delivered clean, structured datasets for downstream analytics and automation\n\nTechnical delivery:\n\n• ETL pipelines for batch data ingestion and transformation\n• SQL data models for operational dashboards and BI reporting\n• Data validation, error handling, and scheduled job orchestration\n• PostgreSQL, MySQL, and SQL Server integration",
    hideVideo: true,
    dataIntegration:
      "Architecture: Source systems → ETL ingestion → transformation & validation → data warehouse → reporting & analytics layer.\n\nStack: SQL, Python, ETL pipelines, PostgreSQL, MySQL, SQL Server, data modeling, data warehousing.",
    tags: [
      { name: "etl", color: "blue-text-gradient" },
      { name: "sql", color: "green-text-gradient" },
      { name: "analytics", color: "pink-text-gradient" },
    ],
    techStack: [
      "SQL",
      "Python",
      "ETL Pipelines",
      "PostgreSQL",
      "MySQL",
      "SQL Server",
      "Data Modeling",
      "Data Warehousing",
    ],
    image: projectSproutData,
    images: [
      { src: projectSproutData, caption: "Data platform — ETL pipeline status, warehouse metrics, and data quality monitoring" },
    ],
    source_code_link: "",
    videoUrl: "",
    liveDemo: "",
    enterprise: true,
  },
  {
    name: "3D Portfolio Site",
    company: "Personal Project",
    companyLogo: null,
    role: "Full-Stack Developer",
    period: "2026",
    category: "Frontend & 3D",
    description:
      "Interactive portfolio built with React, Three.js, and Framer Motion — 3D AI/ML pipeline hero, project modals, and contact form.",
    detailedDescription:
      "Personal portfolio site showcasing AI/ML engineering experience with modern frontend tooling and interactive 3D visuals.\n\nKey highlights:\n\n• 3D AI/ML pipeline visualization built with React Three Fiber and Drei\n• Animated sections and project detail modals powered by Framer Motion\n• Responsive layout with Tailwind CSS and a working contact form\n• Structured content for work history, technical skills, and enterprise project highlights",
    hideVideo: true,
    tags: [
      { name: "react", color: "blue-text-gradient" },
      { name: "three.js", color: "green-text-gradient" },
      { name: "framer-motion", color: "pink-text-gradient" },
    ],
    techStack: [
      "React 18",
      "Vite 5",
      "Three.js",
      "React Three Fiber",
      "Framer Motion",
      "Tailwind CSS 3",
    ],
    image: portfoliopic1,
    images: [
      { src: portfoliopic1, caption: "Portfolio homepage — 3D pipeline hero and project showcase" },
    ],
    source_code_link: "",
    videoUrl: "",
    liveDemo: "",
    enterprise: false,
  },
];

export { expertiseAreas, careerHighlights, technologies, tools, experiences, projects };
